title: Louis-Emmanuel Gires
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > 
  Ing√©nieur Centralien & Entrepreneur
  <br><br>
  <a href="https://www.linkedin.com/in/louis-emmanuel-gires/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
