title: Louis-Emmanuel Gires
logo: "/images/cv2.jpg?raw=true" 
description: > 
  IngÃ©nieur Centralien | Entrepreneur
  <br><br>
  <a href="https://www.linkedin.com/in/louis-emmanuel-gires/">LinkedIn</a> 
  <p><strong>Contact</strong></p>
  <p>ğŸ“§ louis-emmanuel.gires@soprasteria.com</p> 
  <p>â˜ï¸ (+33) 7 63 64 68 58</p>

  
theme: jekyll-theme-minimal
